spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/users/wzx78538350/projects/2#column-5428832 #uri
          search-paths: /** #配置文件目录
      label: master
      username: 78538350@qq.com #github账号
      password: wzx885166!? #github密码

server:
  port: 8862

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/